### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by ha17** [Raikia/Recon-NG-API-Key-Creation#1]
Do you think we could have a README-v4.8.4.md type of a format, where we copy and redo for each version?  These seem to be in flux as the scraping techniques change, at least for the major players.

**Comment by Raikia** [comment]
I agree.  Done!

**Comment by ha17** [comment]
Hi sorry for delayed answer, whole family had the flu. 

The author of recon-ng asked why not update his wiki (which is here: https://bitbucket.org/LaNMaSteR53/recon-ng/wiki/Usage%20Guide#!acquiring-api-keys, thread with repo owner here: https://bitbucket.org/LaNMaSteR53/recon-ng/issues/274/understanding-pwnedlist). What do you think? Should we drop this here and update his wiki in bitbucket?
